/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafkastream.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CustomerOrder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 279178307496100865L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerOrder\",\"namespace\":\"com.kafkastream.model\",\"fields\":[{\"name\":\"customerId\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"phone\",\"type\":\"string\"},{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"orderItemName\",\"type\":\"string\"},{\"name\":\"orderPlace\",\"type\":\"string\"},{\"name\":\"orderPurchaseTime\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerOrder> ENCODER =
      new BinaryMessageEncoder<CustomerOrder>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerOrder> DECODER =
      new BinaryMessageDecoder<CustomerOrder>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CustomerOrder> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CustomerOrder> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CustomerOrder>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this CustomerOrder to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a CustomerOrder from a ByteBuffer. */
  public static CustomerOrder fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence customerId;
  @Deprecated public java.lang.CharSequence firstName;
  @Deprecated public java.lang.CharSequence lastName;
  @Deprecated public java.lang.CharSequence email;
  @Deprecated public java.lang.CharSequence phone;
  @Deprecated public java.lang.CharSequence orderId;
  @Deprecated public java.lang.CharSequence orderItemName;
  @Deprecated public java.lang.CharSequence orderPlace;
  @Deprecated public java.lang.CharSequence orderPurchaseTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerOrder() {}

  /**
   * All-args constructor.
   * @param customerId The new value for customerId
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param email The new value for email
   * @param phone The new value for phone
   * @param orderId The new value for orderId
   * @param orderItemName The new value for orderItemName
   * @param orderPlace The new value for orderPlace
   * @param orderPurchaseTime The new value for orderPurchaseTime
   */
  public CustomerOrder(java.lang.CharSequence customerId, java.lang.CharSequence firstName, java.lang.CharSequence lastName, java.lang.CharSequence email, java.lang.CharSequence phone, java.lang.CharSequence orderId, java.lang.CharSequence orderItemName, java.lang.CharSequence orderPlace, java.lang.CharSequence orderPurchaseTime) {
    this.customerId = customerId;
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.phone = phone;
    this.orderId = orderId;
    this.orderItemName = orderItemName;
    this.orderPlace = orderPlace;
    this.orderPurchaseTime = orderPurchaseTime;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return customerId;
    case 1: return firstName;
    case 2: return lastName;
    case 3: return email;
    case 4: return phone;
    case 5: return orderId;
    case 6: return orderItemName;
    case 7: return orderPlace;
    case 8: return orderPurchaseTime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: customerId = (java.lang.CharSequence)value$; break;
    case 1: firstName = (java.lang.CharSequence)value$; break;
    case 2: lastName = (java.lang.CharSequence)value$; break;
    case 3: email = (java.lang.CharSequence)value$; break;
    case 4: phone = (java.lang.CharSequence)value$; break;
    case 5: orderId = (java.lang.CharSequence)value$; break;
    case 6: orderItemName = (java.lang.CharSequence)value$; break;
    case 7: orderPlace = (java.lang.CharSequence)value$; break;
    case 8: orderPurchaseTime = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return The value of the 'customerId' field.
   */
  public java.lang.CharSequence getCustomerId() {
    return customerId;
  }

  /**
   * Sets the value of the 'customerId' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.CharSequence value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }

  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'phone' field.
   * @return The value of the 'phone' field.
   */
  public java.lang.CharSequence getPhone() {
    return phone;
  }

  /**
   * Sets the value of the 'phone' field.
   * @param value the value to set.
   */
  public void setPhone(java.lang.CharSequence value) {
    this.phone = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'orderItemName' field.
   * @return The value of the 'orderItemName' field.
   */
  public java.lang.CharSequence getOrderItemName() {
    return orderItemName;
  }

  /**
   * Sets the value of the 'orderItemName' field.
   * @param value the value to set.
   */
  public void setOrderItemName(java.lang.CharSequence value) {
    this.orderItemName = value;
  }

  /**
   * Gets the value of the 'orderPlace' field.
   * @return The value of the 'orderPlace' field.
   */
  public java.lang.CharSequence getOrderPlace() {
    return orderPlace;
  }

  /**
   * Sets the value of the 'orderPlace' field.
   * @param value the value to set.
   */
  public void setOrderPlace(java.lang.CharSequence value) {
    this.orderPlace = value;
  }

  /**
   * Gets the value of the 'orderPurchaseTime' field.
   * @return The value of the 'orderPurchaseTime' field.
   */
  public java.lang.CharSequence getOrderPurchaseTime() {
    return orderPurchaseTime;
  }

  /**
   * Sets the value of the 'orderPurchaseTime' field.
   * @param value the value to set.
   */
  public void setOrderPurchaseTime(java.lang.CharSequence value) {
    this.orderPurchaseTime = value;
  }

  /**
   * Creates a new CustomerOrder RecordBuilder.
   * @return A new CustomerOrder RecordBuilder
   */
  public static com.kafkastream.model.CustomerOrder.Builder newBuilder() {
    return new com.kafkastream.model.CustomerOrder.Builder();
  }

  /**
   * Creates a new CustomerOrder RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerOrder RecordBuilder
   */
  public static com.kafkastream.model.CustomerOrder.Builder newBuilder(com.kafkastream.model.CustomerOrder.Builder other) {
    return new com.kafkastream.model.CustomerOrder.Builder(other);
  }

  /**
   * Creates a new CustomerOrder RecordBuilder by copying an existing CustomerOrder instance.
   * @param other The existing instance to copy.
   * @return A new CustomerOrder RecordBuilder
   */
  public static com.kafkastream.model.CustomerOrder.Builder newBuilder(com.kafkastream.model.CustomerOrder other) {
    return new com.kafkastream.model.CustomerOrder.Builder(other);
  }

  /**
   * RecordBuilder for CustomerOrder instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerOrder>
    implements org.apache.avro.data.RecordBuilder<CustomerOrder> {

    private java.lang.CharSequence customerId;
    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    private java.lang.CharSequence email;
    private java.lang.CharSequence phone;
    private java.lang.CharSequence orderId;
    private java.lang.CharSequence orderItemName;
    private java.lang.CharSequence orderPlace;
    private java.lang.CharSequence orderPurchaseTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafkastream.model.CustomerOrder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.customerId)) {
        this.customerId = data().deepCopy(fields()[0].schema(), other.customerId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.phone)) {
        this.phone = data().deepCopy(fields()[4].schema(), other.phone);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.orderId)) {
        this.orderId = data().deepCopy(fields()[5].schema(), other.orderId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.orderItemName)) {
        this.orderItemName = data().deepCopy(fields()[6].schema(), other.orderItemName);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.orderPlace)) {
        this.orderPlace = data().deepCopy(fields()[7].schema(), other.orderPlace);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.orderPurchaseTime)) {
        this.orderPurchaseTime = data().deepCopy(fields()[8].schema(), other.orderPurchaseTime);
        fieldSetFlags()[8] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerOrder instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafkastream.model.CustomerOrder other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.customerId)) {
        this.customerId = data().deepCopy(fields()[0].schema(), other.customerId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.phone)) {
        this.phone = data().deepCopy(fields()[4].schema(), other.phone);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.orderId)) {
        this.orderId = data().deepCopy(fields()[5].schema(), other.orderId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.orderItemName)) {
        this.orderItemName = data().deepCopy(fields()[6].schema(), other.orderItemName);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.orderPlace)) {
        this.orderPlace = data().deepCopy(fields()[7].schema(), other.orderPlace);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.orderPurchaseTime)) {
        this.orderPurchaseTime = data().deepCopy(fields()[8].schema(), other.orderPurchaseTime);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'customerId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerId() {
      return customerId;
    }

    /**
      * Sets the value of the 'customerId' field.
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder setCustomerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.customerId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'customerId' field.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }

    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.firstName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }

    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lastName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }

    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.email = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder clearEmail() {
      email = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'phone' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhone() {
      return phone;
    }

    /**
      * Sets the value of the 'phone' field.
      * @param value The value of 'phone'.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder setPhone(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.phone = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'phone' field has been set.
      * @return True if the 'phone' field has been set, false otherwise.
      */
    public boolean hasPhone() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'phone' field.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder clearPhone() {
      phone = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }

    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.orderId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderItemName' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderItemName() {
      return orderItemName;
    }

    /**
      * Sets the value of the 'orderItemName' field.
      * @param value The value of 'orderItemName'.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder setOrderItemName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.orderItemName = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'orderItemName' field has been set.
      * @return True if the 'orderItemName' field has been set, false otherwise.
      */
    public boolean hasOrderItemName() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'orderItemName' field.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder clearOrderItemName() {
      orderItemName = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderPlace' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderPlace() {
      return orderPlace;
    }

    /**
      * Sets the value of the 'orderPlace' field.
      * @param value The value of 'orderPlace'.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder setOrderPlace(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.orderPlace = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'orderPlace' field has been set.
      * @return True if the 'orderPlace' field has been set, false otherwise.
      */
    public boolean hasOrderPlace() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'orderPlace' field.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder clearOrderPlace() {
      orderPlace = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderPurchaseTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderPurchaseTime() {
      return orderPurchaseTime;
    }

    /**
      * Sets the value of the 'orderPurchaseTime' field.
      * @param value The value of 'orderPurchaseTime'.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder setOrderPurchaseTime(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.orderPurchaseTime = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'orderPurchaseTime' field has been set.
      * @return True if the 'orderPurchaseTime' field has been set, false otherwise.
      */
    public boolean hasOrderPurchaseTime() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'orderPurchaseTime' field.
      * @return This builder.
      */
    public com.kafkastream.model.CustomerOrder.Builder clearOrderPurchaseTime() {
      orderPurchaseTime = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerOrder build() {
      try {
        CustomerOrder record = new CustomerOrder();
        record.customerId = fieldSetFlags()[0] ? this.customerId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.firstName = fieldSetFlags()[1] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastName = fieldSetFlags()[2] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.email = fieldSetFlags()[3] ? this.email : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.phone = fieldSetFlags()[4] ? this.phone : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.orderId = fieldSetFlags()[5] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.orderItemName = fieldSetFlags()[6] ? this.orderItemName : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.orderPlace = fieldSetFlags()[7] ? this.orderPlace : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.orderPurchaseTime = fieldSetFlags()[8] ? this.orderPurchaseTime : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerOrder>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerOrder>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerOrder>
    READER$ = (org.apache.avro.io.DatumReader<CustomerOrder>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
